// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1beta1 "istio.io/client-go/pkg/apis/networking/v1beta1"
	networkingv1beta1 "istio.io/client-go/pkg/applyconfiguration/networking/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOCSPStaples implements OCSPStapleInterface
type FakeOCSPStaples struct {
	Fake *FakeNetworkingV1beta1
	ns   string
}

var ocspstaplesResource = schema.GroupVersionResource{Group: "networking.istio.io", Version: "v1beta1", Resource: "ocspstaples"}

var ocspstaplesKind = schema.GroupVersionKind{Group: "networking.istio.io", Version: "v1beta1", Kind: "OCSPStaple"}

// Get takes name of the oCSPStaple, and returns the corresponding oCSPStaple object, and an error if there is any.
func (c *FakeOCSPStaples) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.OCSPStaple, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ocspstaplesResource, c.ns, name), &v1beta1.OCSPStaple{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.OCSPStaple), err
}

// List takes label and field selectors, and returns the list of OCSPStaples that match those selectors.
func (c *FakeOCSPStaples) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.OCSPStapleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ocspstaplesResource, ocspstaplesKind, c.ns, opts), &v1beta1.OCSPStapleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.OCSPStapleList{ListMeta: obj.(*v1beta1.OCSPStapleList).ListMeta}
	for _, item := range obj.(*v1beta1.OCSPStapleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested oCSPStaples.
func (c *FakeOCSPStaples) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ocspstaplesResource, c.ns, opts))

}

// Create takes the representation of a oCSPStaple and creates it.  Returns the server's representation of the oCSPStaple, and an error, if there is any.
func (c *FakeOCSPStaples) Create(ctx context.Context, oCSPStaple *v1beta1.OCSPStaple, opts v1.CreateOptions) (result *v1beta1.OCSPStaple, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ocspstaplesResource, c.ns, oCSPStaple), &v1beta1.OCSPStaple{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.OCSPStaple), err
}

// Update takes the representation of a oCSPStaple and updates it. Returns the server's representation of the oCSPStaple, and an error, if there is any.
func (c *FakeOCSPStaples) Update(ctx context.Context, oCSPStaple *v1beta1.OCSPStaple, opts v1.UpdateOptions) (result *v1beta1.OCSPStaple, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ocspstaplesResource, c.ns, oCSPStaple), &v1beta1.OCSPStaple{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.OCSPStaple), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOCSPStaples) UpdateStatus(ctx context.Context, oCSPStaple *v1beta1.OCSPStaple, opts v1.UpdateOptions) (*v1beta1.OCSPStaple, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ocspstaplesResource, "status", c.ns, oCSPStaple), &v1beta1.OCSPStaple{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.OCSPStaple), err
}

// Delete takes name of the oCSPStaple and deletes it. Returns an error if one occurs.
func (c *FakeOCSPStaples) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ocspstaplesResource, c.ns, name, opts), &v1beta1.OCSPStaple{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOCSPStaples) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ocspstaplesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.OCSPStapleList{})
	return err
}

// Patch applies the patch and returns the patched oCSPStaple.
func (c *FakeOCSPStaples) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.OCSPStaple, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ocspstaplesResource, c.ns, name, pt, data, subresources...), &v1beta1.OCSPStaple{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.OCSPStaple), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied oCSPStaple.
func (c *FakeOCSPStaples) Apply(ctx context.Context, oCSPStaple *networkingv1beta1.OCSPStapleApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.OCSPStaple, err error) {
	if oCSPStaple == nil {
		return nil, fmt.Errorf("oCSPStaple provided to Apply must not be nil")
	}
	data, err := json.Marshal(oCSPStaple)
	if err != nil {
		return nil, err
	}
	name := oCSPStaple.Name
	if name == nil {
		return nil, fmt.Errorf("oCSPStaple.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ocspstaplesResource, c.ns, *name, types.ApplyPatchType, data), &v1beta1.OCSPStaple{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.OCSPStaple), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeOCSPStaples) ApplyStatus(ctx context.Context, oCSPStaple *networkingv1beta1.OCSPStapleApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.OCSPStaple, err error) {
	if oCSPStaple == nil {
		return nil, fmt.Errorf("oCSPStaple provided to Apply must not be nil")
	}
	data, err := json.Marshal(oCSPStaple)
	if err != nil {
		return nil, err
	}
	name := oCSPStaple.Name
	if name == nil {
		return nil, fmt.Errorf("oCSPStaple.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ocspstaplesResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1beta1.OCSPStaple{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.OCSPStaple), err
}
